spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1
    url: jdbc:mysql://127.0.0.1/spring_data
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


