spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/spring_data?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#logger
logging:
  config: classpath:log4j2-spring.xml

